### ISSUE TITLE
Doesn't work on Windows machines.

### ISSUE THREAD

**Issue by JamieSharpe** [eamon-bell/matlab-runner#1]
Set up all the paths, however doesn't work on windows machines due to how arguments are formatted.

<img width="877" alt="code_2018-02-03_14-19-04" src="https://user-images.githubusercontent.com/1139365/35768001-a98614fe-08ed-11e8-9220-675dd6b37b2d.png">

**Comment by eamonbell** [comment]
What version of Matlab are you using?

**Comment by eamonbell** [comment]
I apologize but the documentation indicates that Matlab will not run in the command prompt. I will update the extension to say Mac only. Sorry for the inconvenience.

**Comment by JamieSharpe** [comment]
Thanks, I was editing the extension and was able to get a working copy after hacking it together. Though my solution isn't convenient, it is better than dealing with the matlab editor.

Thanks for making this. I'll likely use it on another platform.

**Comment by eamonbell** [comment]
You are welcome! If you don't mind me asking, what did you do to get it to work? Maybe I can work it into the extension or invite you to the repo to implement it yourself if you'd like.
