### ISSUE TITLE
Could the code run in the integreted terminal instead of calling the matlab app in Windows?

### ISSUE THREAD

**Issue by RonsinGitHub** [eamon-bell/matlab-runner#2]
Described as the title and please check the gif image attached. How could I run the code as shown in the Demo gif on the main page?
![issure](https://user-images.githubusercontent.com/21312551/36053898-ae6662f2-0dc1-11e8-9018-a986c814bdec.gif)

**Comment by eamonbell** [comment]
Yes, that should be possible. I will update with a potential solution shortly.

**Comment by eamonbell** [comment]
Unfortunately it doesn't seem like matlab supports the command line environment. I will keep looking for a work-around though
