### ISSUE TITLE
could not get to work for win7 and matlab2017b.

### ISSUE THREAD

**Issue by cat2tom** [eamon-bell/matlab-runner#3]
C:\temp42>"C:/Program Files (x86)/Matlab2015a/bin/matlab.exe" -nosplash -nodesktop

C:\temp42>clear 'C:/temp42/test2.m'
'clear' is not recognized as an internal or external command,
operable program or batch file.

C:\temp42>clc
'clc' is not recognized as an internal or external command,
operable program or batch file.

C:\temp42>run 'C:/temp42/test2.m'
'run' is not recognized as an internal or external command,
operable program or batch file.

**Comment by eamonbell** [comment]
Matlab 2015 does not support the command line
