### ISSUE TITLE
Problem Executing A matlab code

### ISSUE THREAD

**Issue by aliassassin1375** [eamon-bell/matlab-runner#4]
here is my error 
![capture](https://user-images.githubusercontent.com/36765179/36595534-bebc4e18-18b7-11e8-9077-10a283611ff0.PNG)

**Comment by eamonbell** [comment]
Can you try setting your default terminal to Command Prompt

**Comment by aliassassin1375** [comment]
thank you
I really appreciate the help

**Comment by eamonbell** [comment]
You're welcome! Let me know if you have any other issues or concerns
