### ISSUE TITLE
Problem with Windows

### ISSUE THREAD

**Issue by IljaK91** [eamon-bell/matlab-runner#5]
It does not seem to work with Windows at the moment. Are there any plans to support Windows at some point?

For example, when I try to run a selection, the following command is sent to the PowerShell:

`"C:\Program Files\MATLAB\R2018a\bin\matlab.exe" -nosplash -nodesktop -r "run('C:\Users\Ilja\Documents\TempFileMatlab.m');"`

But the first part should be 

`"C:\Program Files\MATLAB\R2018a\bin\matlab.exe -nosplash -nodesktop -r "` to work.

**Comment by eamonbell** [comment]
I do not have Matlab installed on my windows machine but I can do my best to create a fix. Or I can invite you to the project if you'd like to take a shot at it.

**Comment by IljaK91** [comment]
I don't know how to make it work, since running 
```
cd "C:\Program Files\MATLAB\R2018a\bin\"
matlab.exe -nosplash -nodesktop -r
```
inside the Powershell opens Matlab in a console-like window. I am not quite sure where to go from here.

I don't have a proper understanding of the underlying mechanics to contribute to this issue, I am sorry.

**Comment by eamonbell** [comment]
I just published an update. Try it out and let me know if it works. Unfortunately Matlab does not support a powershell environment on Windows like they do on OSX so the extension will only be able to show the output in a separate window.

**Comment by IljaK91** [comment]
It does not work, this is what I get:

```
"C:\Program Files\MATLAB\R2018a\bin\matlab.exe" -nosplash -nodesktop -r "run('C:\Users\Ilja\Documents\TempFileMatlab.m');"
In Zeile:1 Zeichen:49
+ "C:\Program Files\MATLAB\R2018a\bin\matlab.exe" -nosplash -nodesktop  ...
+                                                 ~~~~~~~~~
Unerwartetes Token "-nosplash" in Ausdruck oder Anweisung.
In Zeile:1 Zeichen:59
+ ... gram Files\MATLAB\R2018a\bin\matlab.exe" -nosplash -nodesktop -r "run ...
+                                                        ~~~~~~~~~~
Unerwartetes Token "-nodesktop" in Ausdruck oder Anweisung.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
```

**Comment by eamonbell** [comment]
Did you set the matlab-runner.powershell option to 'true' in your settings? There is a description of what to do in the setup section of the extensions home page.

**Comment by IljaK91** [comment]
Thanks, that made it work!

Still, everytime I run the selected code, it opens a new terminal for Matlab. It would be better, if I could send it to the same terminal.

**Comment by eamonbell** [comment]
Unfortunately Matlab doesn't support it on Windows but if they do in the future I will be sure to put out an update
