### ISSUE TITLE
Error: "Could not find path to the matlab executable"

### ISSUE THREAD

**Issue by WillGreen98** [eamon-bell/matlab-runner#6]
Trying to develop MATLAB scripts with VSCode, below are the User Profile Settings to which, the mlint path is as described on the official package documentation.

"matlab.matlabpath": "/Applications/MATLAB_R2018a.app/bin/maci64/MATLAB", or .../bin/matlab
"matlab.mlintpath": "/Applications/MATLAB_R2018a.app/bin/maci64/mlint",

Is using the binary file incorrect? Should I be pointing to a folder instead?

**Comment by eamonbell** [comment]
I'm not sure if I'm understanding your question. The user setting for setting the Matlab path for this extension is 'matlab-runner.matlabPath'. Refer to  the README for information on how to set it up.
