### ISSUE TITLE
Error in Windows

### ISSUE THREAD

**Issue by Jebearssica** [eamon-bell/matlab-runner#7]
+ "D:\MATLAB2018a\bin\matlab" -nosplash -nodesktop -r "run('D:\Project\ ...
it seems that "-nosplash" is a null line.But when I try to run my project in matlab,everythings goes well.is it a mistake in my configuration?
(I mean does it work in Windows system?)
hope to hear your response

I try the line in **cmd** there's no error, and then open MATLAB Command Window and show me the result

I'm very sorry to bother you again.But changing the default section **PowerShell** to **true** might lead contribution.

```
Honestly, I didn't know that really help, because i also change the file path
```

**Comment by eamonbell** [comment]
Can you post a screenshot of the output when you try to run the command?

**Comment by Jebearssica** [comment]
I turn off the setting


Then it shows the error








发送自 Windows 10 版邮件应用

发件人: Eamon Bell
发送时间: 2018年9月18日 2:16
收件人: eamon-bell/matlab-runner
抄送: Jebearssica; Author
主题: Re: [eamon-bell/matlab-runner] Error in Windows (#7)

Can you post a screenshot of the output when you try to run the command?

**Comment by eamonbell** [comment]
Can you post your configuration? Just making sure you followed all the steps

**Comment by Jebearssica** [comment]
I have already solved the problem. Just make sure that set the MATLAB is being executed in powershell(set the value to TRUE)发自我的华为手机-------- 原始邮件 --------主题：Re: [eamon-bell/matlab-runner] Error in Windows (#7)发件人：Eamon Bell 收件人：eamon-bell/matlab-runner 抄送：Jebearssica <446403609@qq.com>,Author Can you post your configuration? Just making sure you followed all the steps

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/eamon-bell/matlab-runner","title":"eamon-bell/matlab-runner","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/eamon-bell/matlab-runner"}},"updates":{"snippets":[{"icon":"PERSON","message":"@eamon-bell in #7: Can you post your configuration? Just making sure you followed all the steps"}],"action":{"name":"View Issue","url":"https://github.com/eamon-bell/matlab-runner/issues/7#issuecomment-422469946"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/eamon-bell/matlab-runner/issues/7#issuecomment-422469946",
"url": "https://github.com/eamon-bell/matlab-runner/issues/7#issuecomment-422469946",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [eamon-bell/matlab-runner] Error in Windows (#7)",
"sections": [
{
"text": "",
"activityTitle": "**Eamon Bell**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@eamon-bell",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"eamon-bell/matlab-runner\",\n\"issueId\": 7,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"eamon-bell/matlab-runner\",\n\"issueId\": 7\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/eamon-bell/matlab-runner/issues/7#issuecomment-422469946"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 380483055\n}"
}
],
"themeColor": "26292E"
}
]
